using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TeamWorkNet.Model
{
  // Generated by Xamasoft JSON Class Generator
  // http://www.xamasoft.com/json-class-generator

  using System;
  using System.Collections.Generic;
  using Newtonsoft.Json;
  using Newtonsoft.Json.Linq;

  namespace TeamWorkNet.Base.Model
  {

    public class Permissions
    {


    }

    public class Person
    {


    }


  }


  }
